### ISSUE TITLE
Implement first user model entity and DTO classes

### ISSUE THREAD

**Issue by Jac00b** [kkania44/wedding-planner#4]
Need clarification

BaseEntity --> with id, creationDate, updateDate, isActive ??
User extends BaseEntity --> keycloakId, userName,  password, firstName, lastName, phoneNumber, ADDRESS OBJECT(different entity)

**Comment by kkania44** [comment]
Myślę, że isActive powinno pójść do UserEntity, a nie BaseEntity. Raczej niepotrzebne jest takie pole we wszystkich encjach
